name: CI

on: [push, pull_request]

jobs:
  x64-ubuntu:
    name: X64-ubuntu
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install libcmocka-dev
      - name: Build
        run: make

      - name: Tests
        run: make test
